/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void sub_10001000();
// int unknown_libname_1(void); weak
int __cdecl BMP_get_bm_color_len(unsigned int a1);
void **__cdecl BMP_get_bm_def(unsigned int a1);
char *__cdecl BMP_get_info(unsigned int a1);
int __cdecl BMP_get_xfrm(unsigned int a1);
int __cdecl FNT_get_fnt_hdr(unsigned int a1);
char __cdecl FNT_pick_font(int a1, int a2, unsigned __int8 a3);
int sub_10001370();
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
signed __int16 __cdecl TXT_get_hndl(char *a1);
char *__cdecl TXT_get_static_string(unsigned __int16 a1);
// int __cdecl abs(int);
// int __cdecl strcmp(const char *, const char *);
// size_t __cdecl strlen(const char *);
signed int __cdecl sub_100019E3(_DWORD *a1);
signed int __cdecl sub_10001A1A(_DWORD *a1);
// _DWORD __cdecl _encode_pointer(_DWORD); weak
// int _encoded_null(void); weak
// _DWORD __cdecl _decode_pointer(_DWORD); weak
// void __cdecl free(void *);
void sub_10002610();
int (*sub_10002ABD())(void);
void __cdecl sub_10002AE1(); // idb
int __cdecl sub_100034B4(int a1);
// int __cdecl _invoke_watson(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __cdecl _invalid_parameter(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int *__cdecl _errno();
int sub_10003962();
int __cdecl sub_10003B1F(int a1);
int __cdecl sub_10003B29(int a1);
int __cdecl sub_10003B33(int a1);
int __cdecl sub_10003C12(int a1);
// int _get_sse2_info(void); weak
int sub_10005C17();
int __cdecl sub_10005C24(int a1, int a2, int a3);
void sub_10005F4B();
// HMODULE __stdcall LoadLibraryA(LPCSTR lpLibFileName);
// FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName);
// void __stdcall DeleteCriticalSection(LPCRITICAL_SECTION lpCriticalSection);

//-------------------------------------------------------------------------
// Data declarations

// extern _UNKNOWN TSK_sch_running; weak
_BYTE byte_1007CD40[332] =
{
  0,
  0,
  1,
  2,
  3,
  3,
  0,
  3,
  4,
  4,
  4,
  4,
  4,
  4,
  5,
  5,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  7,
  6,
  7,
  6,
  7,
  6,
  7,
  6,
  6,
  8,
  8,
  8,
  9,
  0,
  0,
  0,
  0,
  10,
  1,
  11,
  11,
  11,
  11,
  11,
  11,
  12,
  13,
  14,
  12,
  9,
  15,
  0,
  0,
  16,
  17,
  18,
  19,
  0,
  20,
  10,
  10,
  21,
  10,
  22,
  23,
  24,
  24,
  25,
  26,
  27,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  39,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  47,
  48,
  48,
  48,
  48,
  20,
  20,
  20,
  20,
  20,
  9,
  49,
  49,
  50,
  50,
  50,
  51,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  49,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  52,
  14,
  53,
  53,
  14,
  14,
  14,
  14,
  14,
  14,
  54,
  20,
  20,
  20,
  20,
  20,
  55,
  55,
  55,
  56,
  56,
  56,
  20,
  20,
  20,
  57,
  57,
  58,
  58,
  20,
  20,
  59,
  59,
  20,
  20,
  56,
  56,
  55,
  55,
  60,
  60,
  56,
  56,
  56,
  55,
  6,
  56,
  55,
  6,
  56,
  55,
  6,
  56,
  55,
  6,
  61,
  20,
  62,
  63,
  56,
  64,
  65,
  65,
  66,
  67,
  68,
  69,
  70,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  82,
  81,
  61,
  61,
  61,
  61,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  64,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  87,
  97,
  98,
  44,
  99,
  15,
  100,
  61,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  104,
  105,
  106,
  108,
  107,
  105,
  108,
  105,
  104,
  108,
  105,
  105,
  109,
  105,
  108,
  107,
  105,
  105,
  110,
  111,
  61,
  112,
  61,
  110,
  112,
  111,
  110,
  112,
  61,
  111
}; // idb
void *off_1007D630 = &unk_1007CE8C; // weak
void **off_1007D810 = &off_10008460; // weak
_WORD word_1007DD40[332] =
{
  65535,
  65535,
  65535,
  65535,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  65535,
  65535,
  65535,
  65535,
  65535,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  65535,
  54,
  55,
  56,
  57,
  65535,
  65535,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  65535,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  193,
  194,
  195,
  196,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  204,
  205,
  206,
  207,
  208,
  209,
  210,
  211,
  212,
  213,
  214,
  215,
  216,
  217,
  65535,
  218,
  219,
  220,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  221,
  222,
  223,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  233,
  234,
  235,
  236,
  237,
  238,
  239,
  240,
  241,
  242,
  65535,
  243,
  244,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535,
  65535
}; // idb
_UNKNOWN unk_1007DFD8; // weak
_UNKNOWN unk_1007E2B8; // weak
_UNKNOWN unk_1007E2C4; // weak
void *off_100952C0 = &unk_1007E2C8; // weak
_BYTE byte_10095318[24] = { 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 4, 0, 0 }; // idb
char *off_100AE168[6] = { " ", "   MAX LOOK FWD", "   MIN LOOK FWD", "   TIME OUT", " SQK ", "!" }; // weak
_UNKNOWN unk_100B5394; // weak
_UNKNOWN unk_100B6590; // weak
_UNKNOWN unk_100B6598; // weak
int dword_100B7CC0 = 0; // weak
int dword_100B7CDC = 0; // weak
int dword_100B7CE8 = 0; // weak
int dword_100B82B0; // weak
int dword_100B82C0; // weak
int dword_100B82CC; // weak
int dword_100B82D8; // weak
int dword_100B82DC; // weak
int dword_100B82E0; // weak
int dword_100B8328; // weak
int dword_100B832C; // weak
int dword_100B8330; // weak
int dword_100B8334; // weak
int dword_100B8338; // weak
int dword_100B8730; // weak
int dword_100B8750; // weak
int dword_100B8760; // weak
int dword_100B8860; // weak


//----- (10001000) --------------------------------------------------------
void sub_10001000()
{
  ;
}

//----- (10001020) --------------------------------------------------------
int __cdecl BMP_get_bm_color_len(unsigned int a1)
{
  __int64 v1; // rax@3
  void **v3; // [sp+8h] [bp-1Ch]@1
  __int16 j; // [sp+Ch] [bp-18h]@3
  __int16 i; // [sp+10h] [bp-14h]@1
  unsigned __int8 v6; // [sp+1Eh] [bp-6h]@5
  unsigned __int8 v7; // [sp+1Fh] [bp-5h]@1
  int v8; // [sp+20h] [bp-4h]@3

  v7 = 0;
  v3 = BMP_get_bm_def(a1);
  for ( i = 0; i < (signed int)*((_WORD *)v3 + 2); ++i )
  {
    v1 = *((_BYTE *)v3 + 8) * (signed int)*((_WORD *)v3 + 3);
    v8 = (int)*v3 + (((BYTE4(v1) & 7) + (signed int)v1) >> 3) * i;
    for ( j = 0; j < (signed int)*((_WORD *)v3 + 3); ++j )
    {
      v6 = ((1 << *((_BYTE *)v3 + 8)) - 1) & ((signed int)*(_BYTE *)(v8 + ((unsigned int)*((_BYTE *)v3 + 8) * j >> 3)) >> (8 - *((_BYTE *)v3 + 8) - (*((_BYTE *)v3 + 8) * j & 7)));
      if ( v6 != (unsigned __int8)((1 << *((_BYTE *)v3 + 8)) - 1) && v6 > (signed int)v7 )
        v7 = ((1 << *((_BYTE *)v3 + 8)) - 1) & ((signed int)*(_BYTE *)(v8 + ((unsigned int)*((_BYTE *)v3 + 8) * j >> 3)) >> (8 - *((_BYTE *)v3 + 8) - (*((_BYTE *)v3 + 8) * j & 7)));
    }
  }
  return v7 + 1;
}

//----- (10001170) --------------------------------------------------------
void **__cdecl BMP_get_bm_def(unsigned int a1)
{
  void **v2; // [sp+0h] [bp-4h]@1

  v2 = (void **)&unk_1007E2B8;
  if ( a1 < 0x14C )
    v2 = (&off_1007D810)[a1];
  return v2;
}
// 1007D810: using guessed type void **off_1007D810;

//----- (100011A0) --------------------------------------------------------
char *__cdecl BMP_get_info(unsigned int a1)
{
  char *v2; // [sp+0h] [bp-4h]@1

  v2 = (char *)&unk_1007E2C4;
  if ( a1 < 0x14C && (signed int)word_1007DD40[a1] < 245 )
    v2 = (char *)&unk_1007DFD8 + 3 * word_1007DD40[a1];
  return v2;
}

//----- (100011F0) --------------------------------------------------------
int __cdecl BMP_get_xfrm(unsigned int a1)
{
  int v2; // [sp+0h] [bp-4h]@1

  v2 = 0;
  if ( a1 < 0x14C && (signed int)byte_1007CD40[a1] < 113 )
    v2 = (int)*(&off_1007D630 + byte_1007CD40[a1]);
  return v2;
}
// 1007D630: using guessed type void *off_1007D630;

//----- (10001240) --------------------------------------------------------
int __cdecl FNT_get_fnt_hdr(unsigned int a1)
{
  int result; // eax@2

  if ( a1 >= 0x16 )
    result = 0;
  else
    result = (int)*(&off_100952C0 + a1);
  return result;
}
// 100952C0: using guessed type void *off_100952C0;

//----- (10001260) --------------------------------------------------------
char __cdecl FNT_pick_font(int a1, int a2, unsigned __int8 a3)
{
  unsigned int v4; // [sp+0h] [bp-10h]@4
  unsigned int v5; // [sp+4h] [bp-Ch]@1
  char v6; // [sp+8h] [bp-8h]@1
  signed int i; // [sp+Ch] [bp-4h]@1

  v5 = -1;
  v6 = 0;
  for ( i = 0; i < 22; ++i )
  {
    if ( a1 == 9999 )
      v4 = *((_WORD *)*(&off_100952C0 + i) + 10) == 0;
    else
      v4 = abs(a1 - *((_WORD *)*(&off_100952C0 + i) + 10)) << 16;
    if ( a2 != -1 )
      v4 += abs(a2 - (*((_WORD *)*(&off_100952C0 + i) + 12) - *((_WORD *)*(&off_100952C0 + i) + 13))) << 8;
    if ( a3 != 255 )
      v4 += abs(a3 - byte_10095318[i]);
    if ( v4 < v5 )
    {
      v5 = v4;
      v6 = i;
    }
  }
  return v6;
}
// 100952C0: using guessed type void *off_100952C0;

//----- (10001370) --------------------------------------------------------
int sub_10001370()
{
  unknown_libname_1();
  return 0;
}
// 10001010: using guessed type int unknown_libname_1(void);

//----- (10001380) --------------------------------------------------------
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
  if ( fdwReason == 2 )
  {
    if ( dword_100B7CC0 == 1 && !TSK_sch_running )
      dword_100B7CC0 = 0;
    if ( TSK_sch_running && !dword_100B7CC0 )
    {
      sub_10001370();
      dword_100B7CC0 = 1;
    }
  }
  return 1;
}
// 100B7CC0: using guessed type int dword_100B7CC0;

//----- (100013F0) --------------------------------------------------------
signed __int16 __cdecl TXT_get_hndl(char *a1)
{
  signed __int16 v2; // [sp+0h] [bp-8h]@1
  unsigned __int16 i; // [sp+4h] [bp-4h]@2

  v2 = -1;
  if ( strlen(a1) )
  {
    for ( i = 0; (signed int)i < 7306; ++i )
    {
      if ( !strcmp(off_100AE168[i], a1) )
        return i;
    }
  }
  return v2;
}
// 100AE168: using guessed type char *off_100AE168[6];

//----- (10001460) --------------------------------------------------------
char *__cdecl TXT_get_static_string(unsigned __int16 a1)
{
  char *v2; // [sp+0h] [bp-4h]@1

  v2 = (char *)&unk_100B5394;
  if ( (signed int)a1 < 7306 && a1 != 0xFFFF )
    v2 = off_100AE168[a1];
  return v2;
}
// 100AE168: using guessed type char *off_100AE168[6];

//----- (100019E3) --------------------------------------------------------
signed int __cdecl sub_100019E3(_DWORD *a1)
{
  signed int result; // eax@2

  if ( a1 && dword_100B7CDC )
  {
    *a1 = dword_100B7CDC;
    result = 0;
  }
  else
  {
    *_errno() = 22;
    _invalid_parameter(0, 0, 0, 0, 0);
    result = 22;
  }
  return result;
}
// 100035BA: using guessed type int __cdecl _invalid_parameter(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100B7CDC: using guessed type int dword_100B7CDC;

//----- (10001A1A) --------------------------------------------------------
signed int __cdecl sub_10001A1A(_DWORD *a1)
{
  signed int result; // eax@2

  if ( a1 && dword_100B7CDC )
  {
    *a1 = dword_100B7CE8;
    result = 0;
  }
  else
  {
    *_errno() = 22;
    _invalid_parameter(0, 0, 0, 0, 0);
    result = 22;
  }
  return result;
}
// 100035BA: using guessed type int __cdecl _invalid_parameter(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100B7CDC: using guessed type int dword_100B7CDC;
// 100B7CE8: using guessed type int dword_100B7CE8;

//----- (10002610) --------------------------------------------------------
void sub_10002610()
{
  void **v0; // esi@1
  void *v1; // edi@2
  unsigned int i; // eax@3

  v0 = (void **)&dword_100B8760;
  do
  {
    v1 = *v0;
    if ( *v0 )
    {
      for ( i = (unsigned int)v1 + 2048; (unsigned int)v1 < i; i = (unsigned int)*v0 + 2048 )
      {
        if ( *((_DWORD *)v1 + 2) )
          DeleteCriticalSection((LPCRITICAL_SECTION)((char *)v1 + 12));
        v1 = (char *)v1 + 64;
      }
      free(*v0);
      *v0 = 0;
    }
    ++v0;
  }
  while ( (signed int)v0 < (signed int)&dword_100B8860 );
}
// 100B8760: using guessed type int dword_100B8760;
// 100B8860: using guessed type int dword_100B8860;

//----- (10002ABD) --------------------------------------------------------
int (*sub_10002ABD())(void)
{
  int (*result)(void); // eax@1
  int (**v1)(void); // esi@1

  result = (int (*)(void))&unk_100B6590;
  v1 = (int (**)(void))&unk_100B6590;
  if ( &unk_100B6590 < &unk_100B6590 )
  {
    do
    {
      result = *v1;
      if ( *v1 )
        result = (int (*)(void))result();
      ++v1;
    }
    while ( v1 < (int (**)(void))&unk_100B6590 );
  }
  return result;
}

//----- (10002AE1) --------------------------------------------------------
void __cdecl sub_10002AE1()
{
  void (**v0)(void); // esi@1

  v0 = (void (**)(void))&unk_100B6598;
  if ( &unk_100B6598 < &unk_100B6598 )
  {
    do
    {
      if ( *v0 )
        (*v0)();
      ++v0;
    }
    while ( v0 < (void (**)(void))&unk_100B6598 );
  }
}

//----- (100034B4) --------------------------------------------------------
int __cdecl sub_100034B4(int a1)
{
  int result; // eax@1

  result = a1;
  dword_100B82B0 = a1;
  return result;
}
// 100B82B0: using guessed type int dword_100B82B0;

//----- (10003962) --------------------------------------------------------
int sub_10003962()
{
  return _decode_pointer(dword_100B82C0);
}
// 10001D19: using guessed type _DWORD __cdecl _decode_pointer(_DWORD);
// 100B82C0: using guessed type int dword_100B82C0;

//----- (10003B1F) --------------------------------------------------------
int __cdecl sub_10003B1F(int a1)
{
  int result; // eax@1

  result = a1;
  dword_100B82CC = a1;
  return result;
}
// 100B82CC: using guessed type int dword_100B82CC;

//----- (10003B29) --------------------------------------------------------
int __cdecl sub_10003B29(int a1)
{
  int result; // eax@1

  result = a1;
  dword_100B82D8 = a1;
  return result;
}
// 100B82D8: using guessed type int dword_100B82D8;

//----- (10003B33) --------------------------------------------------------
int __cdecl sub_10003B33(int a1)
{
  int result; // eax@1

  result = a1;
  dword_100B82DC = a1;
  return result;
}
// 100B82DC: using guessed type int dword_100B82DC;

//----- (10003C12) --------------------------------------------------------
int __cdecl sub_10003C12(int a1)
{
  int result; // eax@1

  result = a1;
  dword_100B82E0 = a1;
  return result;
}
// 100B82E0: using guessed type int dword_100B82E0;

//----- (10005C17) --------------------------------------------------------
int sub_10005C17()
{
  dword_100B8750 = _get_sse2_info();
  return 0;
}
// 10005BB7: using guessed type int _get_sse2_info(void);
// 100B8750: using guessed type int dword_100B8750;

//----- (10005C24) --------------------------------------------------------
int __cdecl sub_10005C24(int a1, int a2, int a3)
{
  HMODULE v3; // eax@2
  HMODULE v4; // edi@2
  FARPROC v5; // eax@3
  FARPROC v6; // eax@4
  FARPROC v7; // eax@4
  FARPROC v8; // eax@7
  FARPROC v9; // eax@8
  int (*v10)(void); // esi@11
  int (__stdcall *v11)(int, signed int, char *, signed int, char *); // eax@11
  int (__stdcall *v12)(int, signed int, char *, signed int, char *); // edi@11
  int v13; // eax@13
  int (*v14)(void); // eax@22
  int (__stdcall *v15)(int); // eax@25
  int (__stdcall *v16)(int, int, int, int); // eax@27
  char v18; // [sp+10h] [bp-20h]@14
  char v19; // [sp+18h] [bp-18h]@15
  char v20; // [sp+1Ch] [bp-14h]@14
  unsigned int v21; // [sp+20h] [bp-10h]@1
  int v22; // [sp+24h] [bp-Ch]@1
  int v23; // [sp+28h] [bp-8h]@1
  int v24; // [sp+2Ch] [bp-4h]@1

  v23 = _encoded_null();
  v24 = 0;
  v22 = 0;
  v21 = 0;
  if ( !dword_100B8328 )
  {
    v3 = LoadLibraryA("USER32.DLL");
    v4 = v3;
    if ( !v3 )
      return 0;
    v5 = GetProcAddress(v3, "MessageBoxA");
    if ( !v5 )
      return 0;
    dword_100B8328 = _encode_pointer(v5);
    v6 = GetProcAddress(v4, "GetActiveWindow");
    dword_100B832C = _encode_pointer(v6);
    v7 = GetProcAddress(v4, "GetLastActivePopup");
    dword_100B8330 = _encode_pointer(v7);
    if ( sub_100019E3(&v22) )
      _invoke_watson(0, 0, 0, 0, 0);
    if ( v22 == 2 )
    {
      v8 = GetProcAddress(v4, "GetUserObjectInformationA");
      dword_100B8338 = _encode_pointer(v8);
      if ( dword_100B8338 )
      {
        v9 = GetProcAddress(v4, "GetProcessWindowStation");
        dword_100B8334 = _encode_pointer(v9);
      }
    }
  }
  if ( dword_100B8334 == v23
    || dword_100B8338 == v23
    || (v10 = (int (*)(void))_decode_pointer(dword_100B8334),
        v11 = (int (__stdcall *)(int, signed int, char *, signed int, char *))_decode_pointer(dword_100B8338),
        v12 = v11,
        !v10)
    || !v11
    || (v13 = v10()) != 0 && v12(v13, 1, &v18, 12, &v20) && v19 & 1 )
  {
    if ( dword_100B832C != v23 )
    {
      v14 = (int (*)(void))_decode_pointer(dword_100B832C);
      if ( v14 )
      {
        v24 = v14();
        if ( v24 )
        {
          if ( dword_100B8330 != v23 )
          {
            v15 = (int (__stdcall *)(int))_decode_pointer(dword_100B8330);
            if ( v15 )
              v24 = v15(v24);
          }
        }
      }
    }
  }
  else
  {
    if ( sub_10001A1A(&v21) )
      _invoke_watson(0, 0, 0, 0, 0);
    if ( v21 < 4 )
      a3 |= 0x40000u;
    else
      a3 |= 0x200000u;
  }
  v16 = (int (__stdcall *)(int, int, int, int))_decode_pointer(dword_100B8328);
  if ( v16 )
    return v16(v24, a1, a2, a3);
  return 0;
}
// 10001CA2: using guessed type _DWORD __cdecl _encode_pointer(_DWORD);
// 10001D10: using guessed type int _encoded_null(void);
// 10001D19: using guessed type _DWORD __cdecl _decode_pointer(_DWORD);
// 100034BE: using guessed type int __cdecl _invoke_watson(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100B8328: using guessed type int dword_100B8328;
// 100B832C: using guessed type int dword_100B832C;
// 100B8330: using guessed type int dword_100B8330;
// 100B8334: using guessed type int dword_100B8334;
// 100B8338: using guessed type int dword_100B8338;

//----- (10005F4B) --------------------------------------------------------
void sub_10005F4B()
{
  dword_100B8730 = 0;
}
// 100B8730: using guessed type int dword_100B8730;

// ALL OK, 25 function(s) have been successfully decompiled
